apiVersion: v1
kind: ConfigMap
metadata:
  name: druid-mysql-configuration
  namespace: druid
data:
  # mysql_collate.cnf: |-
  #   [mysqld]
  #   character-set-server=utf8
  #   collation-server=utf8_unicode_ci
  # TODO
  druid.sql: |-
    CREATE USER 'druid'@'%' IDENTIFIED BY 'druid';
    CREATE database druid DEFAULT CHARACTER SET utf8mb4;
    GRANT ALL ON druid.* TO 'druid'@'%' IDENTIFIED BY 'druid';

    GRANT ALL ON druid.* TO 'druid'@'localhost' IDENTIFIED BY 'druid';
    GRANT ALL ON druid.* TO 'root'@'localhost' IDENTIFIED BY 'druidroot';
    GRANT ALL ON druid.* TO 'druid'@'druid-druid-cluster-coordinators.druid-operator.svc.cluster.local' IDENTIFIED BY 'druid';
    GRANT ALL ON druid.* TO 'root'@'druid-druid-cluster-coordinators.druid-operator.svc.cluster.local' IDENTIFIED BY 'druidroot';
