apiVersion: v1
kind: Service
metadata:
  name: druid-mysql
  namespace: druid
  labels:
    app: druid-mysql
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    app: druid-mysql