apiVersion: v1
kind: ConfigMap
metadata:
  name: druid-mysql-configuration
  namespace: druid
data:
  mysql_collate.cnf: |-
    [mysqld]
    character-set-server=utf8
    collation-server=utf8_unicode_ci