kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: druid-mysql
  namespace: druid
  labels:
    app: druid-mysql
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"