apiVersion: v1
kind: Service
metadata:
  name: druid-router-lb
  namespace: druid
  labels:
    app: druid
    component: router
spec:
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: druid
    component: router
  type: LoadBalancer