apiVersion: v1
kind: Service
metadata:
  name: druid-zookeeper
  namespace: druid
  labels:
    app: zookeeper
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 2181
      protocol: TCP
      targetPort: client
      
  selector:
    app: zookeeper