apiVersion: v1
kind: Service
metadata:
  name: druid-zookeeper-headless
  namespace: druid
  labels:
    app: zookeeper
spec:
  clusterIP: None
  ports:
    - name: client
      port: 2181
      protocol: TCP
    - name: election
      port: 3888 
      protocol: TCP
    - name: server
      port: 2888
      protocol: TCP
  selector:
    app: zookeeper