apiVersion: v1
kind: Secret
metadata:
  name: superset
  namespace: superset
  labels:
    app: superset
type: Opaque
data:
  init_superset.sh: "L3Vzci9sb2NhbC9iaW4vc3VwZXJzZXQtaW5pdCAtLXVzZXJuYW1lIGFkbWluIC0tZmlyc3RuYW1lIGFkbWluIC0tbGFzdG5hbWUgdXNlciAtLWVtYWlsIGFkbWluQGZhYi5vcmcgLS1wYXNzd29yZCBhZG1pbgpzdXBlcnNldCBydW5zZXJ2ZXI="
