apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  namespace: superset
  labels:
    app: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      name: superset
      labels:
        app: superset
      annotations:
        checksum/secrets: daa537f6baa85070f4863a337df7be09d7fbaaee6e49bbed0b6e113363d660cc
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      volumes:
        - name: superset-secret
          secret:
            secretName: superset
        - name: superset-config
          configMap:
            name: superset-config
        - name: storage-volume
          persistentVolumeClaim:
              claimName: superset-pvc
      containers:
        - name: superset
          image: "amancevice/superset:0.28.1"
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash"]
          args: ["/home/superset/init_superset.sh" ]
          volumeMounts:
            - name: superset-secret
              mountPath: /home/superset/init_superset.sh
              subPath: init_superset.sh
            - name: superset-config
              mountPath: /home/superset/superset_config.py
              subPath: superset_config.py
            - name: storage-volume
              mountPath: /var/lib/superset
          ports:
            - name: http
              containerPort: 8088
              protocol: TCP