apiVersion: v1
kind: Service
metadata:
  name: superset-svc
  namespace: superset
  labels:
    app: superset
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8088
      targetPort: 8088
      protocol: TCP
  selector:
    app: superset