apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: quarkus-test
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 100
  replicas: 3
  replication.factor: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824