apiVersion: v1
kind: Service
metadata:
  name: druid-coordinator
  namespace: druid
  labels:
    app: druid
    component: coordinator
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: druid
    component: coordinator