apiVersion: v1
kind: Service
metadata:
  name: druid-router-lb
  namespace: druid-operator
  labels:
    app: druid
    component: router
spec:
  ports:
    - name: service-port
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: druid
    druid_cr: druid-cluster
    nodeSpecUniqueStr: druid-druid-cluster-routers
  type: LoadBalancer